"""
Catalog build orchestrator for yplot2.

Usage::

    python -m yplot2.catalog_build.build --out-dir catalog [--no-strict]

Collects @catalog capsules via pkgutil, ALWAYS writes catalog.json first
(static index never gated on rendering), then runs the fingerprint gate and
writes CATALOG.md.

Critical ordering guarantee: catalog.json is written before any demo is
executed, so a render failure never makes the static index stale.
"""

import os
import sys
from dataclasses import dataclass

from .collect import ImportFailure, collect_records
from .fingerprint import FingerprintResult, fingerprint_capsule
from .records import CapsuleRecord, catalog_to_json


@dataclass(frozen=True)
class BuildReport:
    """Summary of a catalog build."""

    n_capsules: int
    import_failures: tuple[ImportFailure, ...]
    blocking_failures: tuple[str, ...]
    catalog_json_path: str
    catalog_md_path: str


def _write_catalog_json(records: list[CapsuleRecord], out_dir: str) -> str:
    """Serialize records to JSON and write to *out_dir*/catalog.json.

    Args:
        records: All collected CapsuleRecords.
        out_dir: Output directory path.

    Returns:
        Absolute path to the written file.
    """
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "catalog.json")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(catalog_to_json(records))
    return path


def _capsule_md_block(
    rec: CapsuleRecord,
    result: FingerprintResult | None,
    thumbs_dir: str,
) -> str:
    """Return a Markdown block for one capsule.

    Args:
        rec: Capsule record to describe.
        result: Fingerprint result (may be None when demo was not run).
        thumbs_dir: Directory where thumbnails are stored.

    Returns:
        Markdown string for the capsule entry.
    """
    lines = [
        f"### `{rec.import_path}`",
        "",
        f"**Tags:** {', '.join(rec.tags)}  ",
        f"**Data shape:** `{rec.data_shape}`  ",
        f"**Kind:** `{rec.kind}`",
        "",
    ]
    if rec.summary:
        lines += [rec.summary, ""]
    thumb_file = os.path.join(thumbs_dir, f"{rec.name}.png")
    if result and result.thumbnail_ok and os.path.isfile(thumb_file):
        lines += [f"![{rec.name} thumbnail](thumbs/{rec.name}.png)", ""]
    return "\n".join(lines)


def _write_catalog_md(
    records: list[CapsuleRecord],
    results: dict[str, FingerprintResult],
    out_dir: str,
) -> str:
    """Write CATALOG.md grouped by category to *out_dir*.

    Args:
        records: All collected CapsuleRecords.
        results: Mapping of capsule name → FingerprintResult.
        out_dir: Output directory path.

    Returns:
        Absolute path to the written file.
    """
    thumbs_dir = os.path.join(out_dir, "thumbs")
    by_category: dict[str, list[CapsuleRecord]] = {}
    for rec in sorted(records, key=lambda r: (r.category, r.name)):
        by_category.setdefault(rec.category, []).append(rec)

    lines = [
        "# yplot2 Catalog",
        "",
        "Auto-generated by `python -m yplot2.catalog_build.build`.",
        "",
    ]
    for category, recs in sorted(by_category.items()):
        lines += [f"## {category.title()}", ""]
        for rec in recs:
            lines.append(_capsule_md_block(rec, results.get(rec.name), thumbs_dir))

    path = os.path.join(out_dir, "CATALOG.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


def _run_fingerprints(
    records: list[CapsuleRecord],
    out_dir: str,
) -> tuple[dict[str, FingerprintResult], list[str]]:
    """Run the fingerprint gate on all records with a demo.

    Args:
        records: All collected CapsuleRecords.
        out_dir: Output directory (thumbs go into <out_dir>/thumbs/).

    Returns:
        Tuple of (results dict, list of blocking failure names).
    """
    thumbs_dir = os.path.join(out_dir, "thumbs")
    os.makedirs(thumbs_dir, exist_ok=True)

    results: dict[str, FingerprintResult] = {}
    blocking: list[str] = []

    for rec in records:
        if not rec.has_demo:
            continue
        thumb_path = os.path.join(thumbs_dir, f"{rec.name}.png")
        result = fingerprint_capsule(rec, thumb_path=thumb_path)
        results[rec.name] = result
        if result.blocking_failed:
            blocking.append(rec.name)

    return results, blocking


def build_catalog(out_dir: str) -> BuildReport:
    """Collect capsules, ALWAYS write catalog.json, then fingerprint + write CATALOG.md.

    The critical ordering guarantee: catalog.json is written before any demo
    runs, so a render failure never makes the static index stale. If collection
    itself partially fails (e.g., a subpackage init raises), the failures are
    recorded and catalog.json is written from whatever was successfully collected.

    Args:
        out_dir: Output directory for catalog.json, CATALOG.md, and thumbs/.

    Returns:
        BuildReport summarising the build.
    """
    records: list[CapsuleRecord] = []
    import_failures: list[ImportFailure] = []
    try:
        records, import_failures = collect_records()
    except Exception as exc:
        import_failures.append(ImportFailure(module="<collect>", error=repr(exc)))

    # ALWAYS write catalog.json first — before any demo execution
    json_path = _write_catalog_json(records, out_dir)

    # Then run fingerprint gate (may fail; catalog.json is already written)
    results, blocking = _run_fingerprints(records, out_dir)

    md_path = _write_catalog_md(records, results, out_dir)

    return BuildReport(
        n_capsules=len(records),
        import_failures=tuple(import_failures),
        blocking_failures=tuple(blocking),
        catalog_json_path=json_path,
        catalog_md_path=md_path,
    )


def main(argv: list[str] | None = None) -> int:
    """CLI: ``python -m yplot2.catalog_build.build --out-dir catalog [--no-strict]``.

    Exits 1 if any blocking fingerprint failure occurred, else 0.

    Args:
        argv: Argument list (default: sys.argv[1:]).

    Returns:
        0 on success, 1 on any blocking failure.
    """
    import argparse

    parser = argparse.ArgumentParser(description="Build the yplot2 capsule catalog.")
    parser.add_argument("--out-dir", default="catalog", help="Output directory")
    parser.add_argument(
        "--no-strict",
        action="store_true",
        help="Do not exit non-zero on fingerprint failures",
    )
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])
    strict = not args.no_strict

    report = build_catalog(args.out_dir)

    print(f"Capsules collected: {report.n_capsules}")
    print(f"catalog.json: {report.catalog_json_path}")
    print(f"CATALOG.md:   {report.catalog_md_path}")

    if report.import_failures:
        print(f"Import failures: {len(report.import_failures)}", file=sys.stderr)
        for f in report.import_failures:
            print(f"  {f.module}: {f.error}", file=sys.stderr)

    if report.blocking_failures:
        print(f"Style gate failures: {report.blocking_failures}", file=sys.stderr)
        if strict:
            return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
